base/api/urls.py
from django.urls import path

from base.api import views

urlpatterns = [
    path("", views.get_routes),
    path("rooms/", views.get_rooms),
    path("rooms/<str:pk>", views.get_room)
]

base/urls.py
from django.urls import path

from base import views

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_page, name="register"),

    path("", views.home_page, name="home"),
    path("room/<str:pk>", views.room_page, name="room"),
    path("profile/<str:pk>", views.user_profile, name="user-profile"),

    path("create-room/", views.create_room, name="create-room"),
    path("update-room/<str:pk>", views.update_room, name="update-room"),
    path("delete-room/<str:pk>", views.delete_room, name="delete-room"),

    path("delete-message/<str:pk>", views.delete_message, name="delete-message"),

    path("update-user/", views.update_user, name="update-user"),
    path("reset-avatar/", views.reset_avatar, name="reset-avatar"),

    path("topics/", views.topics_page, name="topics"),
    path("activity/", views.activity_page, name="activity"),
]

pydiscord/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("api/", include("base.api.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from django.db import models


def avatar_upload_location(instance, filename):
    ext = filename.split('.')[-1]
    new_name = uuid.uuid4().hex[:16]
    return f"avatars/{new_name}.{ext}"


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(
        null=True,
        default="avatar.svg",
        upload_to=avatar_upload_location,
        validators=[FileExtensionValidator(["svg", "jpeg", "jpg", "png"])],
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name="participants", blank=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.body[0: 50]

base/forms.py
from django import forms as forms
from django.contrib.auth.forms import UserCreationForm

from base.models import Room, User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["name", "username", "email", "password1", "password2"]


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = "__all__"
        exclude = ["host", "participants"]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["avatar", "name", "username", "bio"]

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response

from base.api.serializers import RoomSerializer
from base.models import Room


@api_view(["GET"])
def get_routes(request):
    routes = [
        "GET /api",
        "GET /api/rooms",
        "GET /api/rooms/:id"
    ]
    return Response(routes)


@api_view(["GET"])
def get_rooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(["GET"])
def get_room(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/views.py
import os

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect

import pydiscord.settings as settings
from base.forms import RoomForm, UserForm, MyUserCreationForm
from base.models import Room, Topic, Message, User


def login_page(request):
    page = "login"
    if request.user.is_authenticated:
        return redirect("home")

    if request.method == "POST":
        email = request.POST.get("email").lower()
        password = request.POST.get("password")

        try:
            User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            if user:
                login(request, user)
                return redirect("home")
            else:
                messages.error(request, f"Password for user: {email} is incorrect")
        except User.DoesNotExist:
            messages.error(request, f"User: {email} does not exits")

    context = {"page": page}
    return render(request, "base/login_register.html", context)


def logout_user(request):
    logout(request)
    return redirect("home")


def register_page(request):
    page = "register"
    form = MyUserCreationForm()

    if request.method == "POST":
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user=user)

            return redirect("home")
        else:
            messages.error(request, f"An error occurred during user registration:")
            for field in form:
                if field.errors:
                    messages.error(request, f"\tField Error: '{field.name}'")
                    for error in field.errors:
                        messages.error(request, f"\t\t'{error}'\n")

    context = {"page": page, "form": form}
    return render(request, "base/login_register.html", context)


def home_page(request):
    q = request.GET.get("q")
    q = q if q else ""
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()[:5]
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))

    context = {"rooms": rooms, "topics": topics, "room_count": room_count, "room_messages": room_messages}
    return render(request, "base/home.html", context)


def topics_page(request):
    q = request.GET.get("q")
    q = q if q else ""
    topics = Topic.objects.filter(name__icontains=q)

    context = {"topics": topics}
    return render(request, "base/topics.html", context)


def activity_page(request):
    room_messages = Message.objects.all()
    context = {"room_messages": room_messages}
    return render(request, "base/activity.html", context)


def room_page(request, pk):
    _room = Room.objects.get(id=pk)
    room_messages = _room.message_set.all()
    participants = _room.participants.all()

    if request.method == "POST":
        Message.objects.create(
            user=request.user,
            room=_room,
            body=request.POST.get("body")
        )
        if request.user not in participants:
            _room.participants.add(request.user)
        return redirect("room", pk=_room.id)

    context = {"room": _room, "room_messages": room_messages, "participants": participants}
    return render(request, "base/room.html", context)


@login_required(login_url="login")
def create_room(request):
    form = RoomForm()
    topics = Topic.objects.all()

    if request.method == "POST":
        topic_name = request.POST.get("topic")
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get("name"),
            description=request.POST.get("description"),
        )
        return redirect("home")

    context = {"form": form, "topics": topics}
    return render(request, "base/room_form.html", context)


@login_required(login_url="login")
def update_room(request, pk):
    _room = Room.objects.get(id=pk)
    form = RoomForm(instance=_room)
    topics = Topic.objects.all()

    if request.user != _room.host:
        return HttpResponse("You are not allowed to edit this room!")

    if request.method == "POST":
        topic_name = request.POST.get("topic")
        topic, created = Topic.objects.get_or_create(name=topic_name)

        _room.name = request.POST.get("name")
        _room.topic = topic
        _room.description = request.POST.get("description")
        _room.save()

        return redirect("home")

    context = {"form": form, "topics": topics, "room": _room}
    return render(request, "base/room_form.html", context)


@login_required(login_url="login")
def delete_room(request, pk):
    _room = Room.objects.get(id=pk)

    if request.user != _room.host:
        return HttpResponse("You are not allowed to delete this room!")

    if request.method == "POST":
        _room.delete()
        return redirect("home")

    context = {"obj": _room}
    return render(request, "base/delete.html", context)


@login_required(login_url="login")
def delete_message(request, pk):
    _message = Message.objects.get(id=pk)

    if request.user != _message.user:
        return HttpResponse("You are not allowed here!")

    if request.method == "POST":
        _message.delete()
        return redirect("home")

    context = {"obj": _message}
    return render(request, "base/delete.html", context)


def user_profile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()

    context = {"user": user, "rooms": rooms, "room_messages": room_messages, "topics": topics}
    return render(request, "base/profile.html", context)


@login_required(login_url="login")
def update_user(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == "POST":
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("user-profile", pk=user.id)
        else:
            messages.error(request, f"An error occurred during profile change:")
            for field in form:
                if field.errors:
                    messages.error(request, f"\tField Error: '{field.name}'")
                    for error in field.errors:
                        messages.error(request, f"\t\t'{error}'\n")

    context = {"form": form}
    return render(request, "base/update-user.html", context)


@login_required(login_url="login")
def reset_avatar(request):
    user: User = request.user
    if request.method == "POST":
        default_avatar_path = os.path.join(settings.MEDIA_ROOT, 'avatar.svg')
        with open(default_avatar_path, "rb") as default_avatar:
            new_avatar_name = f"{user.avatar.url.split('.')[0]}.svg"
            user.avatar.delete(save=False)
            user.avatar.save(new_avatar_name, default_avatar)

        return redirect("user-profile", pk=user.id)

    context = {"user": user}
    return render(request, "base/reset_avatar.html", context)

base/templates/base/activity.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <main class="layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg viewBox="0 0 32 32">
                                <use href="{% static "images/icons/arrow-left.svg" %}#arrow_left_icon"></use>
                            </svg>
                        </a>
                        <h3>Recent Activities</h3>
                    </div>
                </div>
                {% for message in room_messages %}
                    <div class="activities__box">
                        <div class="activities__boxHeader roomListRoom__header">
                            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                                <div class="avatar avatar--small">
                                    <img src="{{ message.user.avatar.url }}" alt="user avatar"/>
                                </div>
                                <p>
                                    @{{ message.user.username }}
                                    <span>{{ message.created|timesince }} ago</span>
                                </p>
                            </a>

                            {% if request.user == message.user %}
                                <div class="roomListRoom__actions">
                                    <a href="{% url 'delete-message' message.id %}">
                                        <svg viewBox="0 0 32 32">
                                            <use href="{% static "images/icons/remove.svg" %}#remove_icon"></use>
                                        </svg>
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                        <div class="activities__boxContent">
                            <p>replied to post “<a href="{% url 'room' message.room.id %}">{{ message.room }}</a>”</p>
                            <div class="activities__boxRoomContent">
                                {{ message.body }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock content %}

base/templates/base/activity_component.html
{% load static %}

<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
        <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                    <div class="avatar avatar--small">
                        <img src="{{ message.user.avatar.url }}" alt="user avatar"/>
                    </div>
                    <p>
                        @{{ message.user.username }}
                        <span>{{ message.created|timesince }} ago</span>
                    </p>
                </a>

                {% if request.user == message.user %}
                    <div class="roomListRoom__actions">
                        <a href="{% url 'delete-message' message.id %}">
                            <svg viewBox="0 0 32 32">
                                <use href="{% static "images/icons/remove.svg" %}#remove_icon"></use>
                            </svg>
                        </a>
                    </div>
                {% endif %}
            </div>
            <div class="activities__boxContent">
                <p>replied to post “<a href="{% url 'room' message.room.id %}">{{ message.room }}</a>”</p>
                <div class="activities__boxRoomContent">
                    {{ message.body }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

base/templates/base/delete.html
{% extends "main.html" %}
{% load static %}

{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg viewBox="0 0 32 32">
                                <use href="{% static "images/icons/arrow-left.svg" %}#arrow_left_icon"></use>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" method="post" action="">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{ obj }}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

base/templates/base/feed_component.html
{% load static %}

{% for room in rooms %}
    <div class="roomListRoom">
        <div class="roomListRoom__header">
            <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{ room.host.avatar.url }}" alt="host avatar"/>
                </div>
                <span>@{{ room.host.username }}</span>
            </a>
            <div class="roomListRoom__actions">
                <span>{{ room.created | timesince }} ago</span>
            </div>
        </div>
        <div class="roomListRoom__content">
            <a href="{% url 'room' room.id %}">{{ room.name }}</a>
            <p>
                {{ room.description }}
            </p>
        </div>
        <div class="roomListRoom__meta">
            <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
                <svg viewBox="0 0 32 32">
                    <use href="{% static "images/icons/user-group.svg" %}#user_group_icon"></use>
                </svg>
                {{ room.participants.all.count }} Joined
            </a>
            <p class="roomListRoom__topic">{{ room.topic.name }}</p>
        </div>
    </div>
{% endfor %}

base/templates/base/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <main class="layout layout--3">
        <div class="container">
            <!-- Topics Start -->
            {% include 'base/topics_component.html' %}
            <!-- Topics End -->

            <!-- Room List Start -->
            <div class="roomList">
                <div class="mobile-menu">
                    <form action="{% url 'home' %}" method="get" class="header__search">
                        <label>
                            <svg viewBox="0 0 32 32">
                                <use href="{% static "images/icons/search.svg" %}#search_icon"></use>
                            </svg>
                            <input name="q" placeholder="Search for posts"/>
                        </label>
                    </form>
                    <div class="mobile-menuItems">
                        <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
                        <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
                    </div>
                </div>
                <div class="roomList__header">
                    <div>
                        <h2>Room</h2>
                        <p>{{ room_count }} Rooms available</p>
                    </div>
                    <a class="btn btn--main" href="{% url 'create-room' %}">
                        <svg viewBox="0 0 32 32">
                            <use href="{% static "images/icons/add.svg" %}#add_icon"></use>
                        </svg>
                        Create Conversation
                    </a>
                </div>
                {% include 'base/feed_component.html' %}
            </div>
            <!-- Room List End -->

            <!-- Activities Start -->
            {% include 'base/activity_component.html' %}
            <!-- Activities End -->
        </div>
    </main>
{% endblock %}

base/templates/base/login_register.html
{% extends "main.html" %}
{% load static %}

{% block content %}
    <main class="auth layout">

        {% if page == 'login' %}
            <div class="container">
                <div class="layout__box">
                    <div class="layout__boxHeader">
                        <div class="layout__boxTitle">
                            <h3>Login</h3>
                        </div>
                    </div>
                    <div class="layout__body">
                        <h2 class="auth__tagline">Get inside and get wild</h2>

                        <form class="form" method="post" action="">
                            {% csrf_token %}
                            <div class="form__group form__group">
                                <label for="room_name">Email</label>
                                <input id="username" name="email" type="text" placeholder="e.g. anon420@coolmail.com"/>
                            </div>
                            <div class="form__group">
                                <label for="password">Password</label>
                                <input
                                        id="password"
                                        name="password"
                                        type="password"
                                        placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                                />
                            </div>

                            <button class="btn btn--main" type="submit">
                                <svg viewBox="0 0 32 32">
                                    <use href="{% static "images/icons/lock.svg" %}#lock_icon"></use>
                                </svg>
                                Login
                            </button>
                        </form>

                        <div class="auth__action">
                            <p>Haven't signed up yet?</p>
                            <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="container">
                <div class="layout__box">
                    <div class="layout__boxHeader">
                        <div class="layout__boxTitle">
                            <h3>Register</h3>
                        </div>
                    </div>
                    <div class="layout__body">
                        <h2 class="auth__tagline">Get inside and get wild</h2>

                        <form class="form" method="post" action="">
                            {% csrf_token %}

                            {% for field in form %}
                                <div class="form__group form__group">
                                    <label for="room_name">{{ field.label }}</label>
                                    {{ field }}
                                    {{ field.help_text }}
                                </div>
                            {% endfor %}

                            <button class="btn btn--main" type="submit">
                                <svg viewBox="0 0 32 32">
                                    <use href="{% static "images/icons/lock.svg" %}#lock_icon"></use>
                                </svg>
                                Register
                            </button>
                        </form>

                        <div class="auth__action">
                            <p>Already signed up?</p>
                            <a href="{% url 'login' %}" class="btn btn--link">Sign In</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </main>
{% endblock content %}

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}
    <main class="profile-page layout layout--3">
        <div class="container">
            <!-- Topics Start -->
            {% include 'base/topics_component.html' %}
            <!-- Topics End -->

            <!-- Room List Start -->
            <div class="roomList">
                <div class="profile">
                    <div class="profile__avatar">
                        <div class="avatar avatar--large active">
                            <img src="{{ user.avatar.url }}" alt="user avatar"/>
                        </div>
                    </div>
                    <div class="profile__info">
                        <h3>{{ user.username }}</h3>
                        <p>@{{ user.username }}</p>
                        {% if request.user == user %}
                            <a href="{% url 'update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
                        {% endif %}
                    </div>
                    <div class="profile__about">
                        <h3>About</h3>
                        <p>
                            {% if user.bio %}
                                {{ user.bio }}
                            {% else %}
                                Not filled up yet.
                            {% endif %}
                        </p>
                    </div>
                </div>

                <div class="roomList__header">
                    <div>
                        <h2>Conversations Hosted by {{ user.username }}</h2>
                    </div>
                </div>

                {% include 'base/feed_component.html' %}
            </div>
            <!-- Room List End -->

            <!-- Activities Start -->
            {% include 'base/activity_component.html' %}
            <!-- Activities End -->
        </div>
    </main>
{% endblock content %}

base/templates/base/reset_avatar.html
{% extends "main.html" %}
{% load static %}

{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg viewBox="0 0 32 32">
                                <use href="{% static "images/icons/arrow-left.svg" %}#arrow_left_icon"></use>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" method="post" action="">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to reset your Avatar?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

base/templates/base/topics_component.html
{% load static %}
<div class="topics">
    <div class="topics__header">
        <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
        <li>
            <a href="{% url 'home' %}" class="active">All <span>{{ topics.count }}</span></a>
        </li>
        {% for topic in topics %}
            <li>
                <a href="{% url 'home' %}?q={{ topic.name }}">{{ topic.name }}
                    <span>{{ topic.room_set.all.count }}</span></a>
            </li>
        {% endfor %}
    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
        More
        <svg viewBox="0 0 32 32">
            <use href="{% static "images/icons/chevron-down.svg" %}#chevron_down_icon"></use>
        </svg>
    </a>
</div>

base/templates/base/update-user.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg viewBox="0 0 32 32">
                                <use href="{% static "images/icons/arrow-left.svg" %}#arrow_left_icon"></use>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form__group">
                                <label for="profile_pic">{{ field.label }}</label>
                                {% if field.name == 'avatar' %}
                                    Currently:<br/>
                                    <div class="avatar avatar--large active">
                                        <img src="{{ form.initial.avatar.url }}" alt="current avatar">

                                    </div>
                                    <br/>
                                    Change:<br/>
                                    <input type="file" name="avatar" accept="image/*" id="id_avatar">
                                {% else %}
                                    {{ field }}

                                {% endif %}
                            </div>
                        {% endfor %}

                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'reset-avatar' %}">Reset avatar</a>
                            <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}